config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    resources :monitems
  end
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :sex, :nation, :occupation, presence: true
  has_one_attached :avatar
  paginates_per 10
  def self.ransackable_attributes(auth_object = nil)
    ["alias_name", "biographical_text", "birthday", "birthplace", "deathdate", "name", "nation", "occupation", "sex"]
  end
  has_many :monitems
end

app/models/monitem.rb
class Monitem < ApplicationRecord
  belongs_to :item
  validates :biographical_text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: %i[ create edit update destroy ]
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @q = Item.ransack(params[:q])
    @people = @q.result(distinct: true).page(params[:page])
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "数据成功保存。" }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "数据成功更新。" }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "数据已删除。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:avatar, :name, :alias_name, :sex, :nation, :birthday, :deathdate, :birthplace, :occupation, :biographical_text)
    end
end

app/controllers/monitems_controller.rb
class MonitemsController < ApplicationController
  before_action :authenticate_user!, only: %i[ create edit update destroy ]
  before_action :set_monitem, only: %i[ show edit update destroy ]

  # GET /monitems or /monitems.json
  def index
    @item = Item.find(params[:item_id])
    @monitems = @item.monitems.all
  end

  # GET /monitems/1 or /monitems/1.json
  def show
  end

  # GET /monitems/new
  def new
    @item = Item.find(params[:item_id])
    @monitem = @item.monitems.new
  end

  # GET /monitems/1/edit
  def edit
  end

  # POST /monitems or /monitems.json
  def create
    @item = Item.find(params[:item_id])
    @monitem = Monitem.new(monitem_params)

    respond_to do |format|
      if @monitem.save
        format.html { redirect_to [@monitem.item, @monitem], notice: "该蒙古文信息已保存" }
        format.json { render :show, status: :created, location: @monitem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monitems/1 or /monitems/1.json
  def update
    respond_to do |format|
      if @monitem.update(monitem_params)
        format.html { redirect_to item_monitem_url(@monitem.item, @monitem), notice: "该蒙古文信息已更新。" }
        format.json { render :show, status: :ok, location: @monitem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monitems/1 or /monitems/1.json
  def destroy
    @monitem.destroy

    respond_to do |format|
      format.html { redirect_to item_url(@monitem.item), notice: "该蒙古文信息已删除。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monitem
      @item = Item.find(params[:item_id])
      @monitem = @item.monitems.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monitem_params
      params.require(:monitem).permit(:item_id, :name, :alias_name, :nation, :birthplace, :occupation, :biographical_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/monitems_helper.rb
module MonitemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
<div class="field is-horizontal">
  <div class="field-label">
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <% if item.errors.any? %>
          <div style="color: red">
            <h2>保存数据时发现 <%= pluralize(item.errors.count, "个错误") %>：</h2>

            <ul>
              <% item.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>
<div class="field is-horizontal">  
  <div class="field-label is-normal">
    <%= form.label "头像", class: "label" %>
  </div>
  <div class="field-body">
    <div class="file has-name">
      <label class="file-label">
        <%= form.file_field :avatar, class: "file-input"%>
        <span class="file-cta">
          <span class="file-icon">
            <i class="fas fa-upload"></i>
          </span>
          <span class="file-label">
            选择一个照片文件……
          </span>
        </span>
        <span class="file-name">
          <% if @item.avatar.attached? %>
          <%= @item.avatar.filename %>
          <% else %>
          没有上传头像
          <% end %>
        </span>
      </label>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :name, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_field :name, class: "input" %>
      </div>
      <p class="help is-danger">
        必填项，填写常用名
      </p>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :alias_name, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_field :alias_name, class: "input" %>
      </div>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label">
    <%= form.label "sex", class: "label" %>
  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
        <label class="radio">
          <%= form.radio_button :sex, "male" %>
          男
        </label>
        <label class="radio">
          <%= form.radio_button :sex, "female" %>
          女
        </label>
      </div>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :nation, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_field :nation, class: "input" %>
      </div>
      <p class="help is-danger">
        中国专家学者使用此项填写民族，如“**族”，国外专家填写国籍即可
      </p>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :birthday, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_field :birthday, class: "input" %>
      </div>
      <p class="help is-danger">
        有则必填，格式为 YYYY-MM-DD，不清楚则用“0”代替
      </p>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :deathdate, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_field :deathdate, class: "input" %>
      </div>
      <p class="help is-info">
        格式为 YYYY-MM-DD，不清楚则用“0”代替
      </p>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :birthplace, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_field :birthplace, class: "input" %>
      </div>
      <p class="help is-info">
        如出生地为历史行政区划，请在括号中对现在地址加以说明
      </p>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :occupation, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_field :occupation, class: "input" %>
      </div>
      <p class="help is-danger">
        必填项，填写主要从事职业或者擅长学科等
      </p>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <%= form.label :biographical_text, class: "label" %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.text_area :biographical_text, class: "textarea" %>
      </div>
      <p class="help is-info">
        支持 Markdown 格式
      </p>
    </div>
  </div>
</div>
<div class="field is-horizontal">
  <div class="field-label">
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= form.submit class: "button is-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class="columns my-6">
  <div class="column is-4 has-text-right">
    <% if item.avatar.attached? %>
    <%=image_tag item.avatar %>
    <% end %>
    <% if item.monitems.size > 0 %>
    <div class="mongolian-info">
      <%=link_to t(".mongolian_info"), item_monitem_path(item, item.monitems.first), class: "button" %>
    </div>
    <% end %>
  </div>
  
  <div class="column is-8 content">
   <p>
   <strong><%= item.name %></strong>
   <% unless item.alias_name.strip == "" %>
     <%= t(".alias_name") %><%= item.alias_name %>
   <% end %>。
    （
    <%= item.birthday %>
    ——
    <%= item.deathdate %>），
    <% if item.sex == "male" %>男<% else %>女<% end %>，
    <%= item.nation %>，
        出生于<%= item.birthplace %>。
        <%= item.occupation %>。
      </p>

     <%= Kramdown::Document.new(item.biographical_text).to_html.html_safe %>
  </div>
  
</div>

app/views/items/edit.html.erb
<div class="title is-3 mt-6"><%= t(".editing_item") %></div>

<%= render "form", item: @item %>

app/views/items/index.html.erb
<%= search_form_for @q do |f| %>
<div class="field has-addons has-addons-centered my-6 pt-6">

    <p class="control">
    <%= f.search_field :name_cont, class: "input" %>      
    </p>
    <p class="control">
      <%= f.submit "检索", class: "button is-primary" %>
    </p>
</div>
<% end %>

<div class="content">
  <ul class="list">
  <% @people.each do |person| %>
  <li class="list-item"><%= link_to person.name, person %></li>
  <% end %>
  </ul>
</div>

<div class="paginate">
  <p class="mt-6 pt-6 pb-6">
  <%= paginate @people %>
  </p>
</div>

app/views/items/new.html.erb
<div class="title is-3 mt-6"><%= t(".new_item") %></div>

<%= render "form", item: @item %>

app/views/items/show.html.erb
<%= render @item %>
<% if user_signed_in? %>
<div class="columns is-mobile is-centered">
  <div class="column">
    <%= link_to t(".edit_this_item"), edit_item_path(@item), class: "button is-info" %> 
  </div>
  <div class="column">
      <%= button_to t(".destroy_this_item"), @item, method: :delete, class: "button is-danger", data: {"turbo-confirm": "您确认要删除该信息吗？"} %>
  </div>
  <div class="column">
       <% if @item.monitems.size == 0 %>
    <%= link_to t(".add_mongolian_item"), new_item_monitem_path(@item), class: "button is-link" %>
    <% end %>
  </div>
   
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= t(".expert") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://docs.rubyist.cn/bulma/vendor/fontawesome-free-5.15.2-web/css/all.min.css">
  </head>

  <body>
    <h1>
     <a href="<%= root_path %>"></a>
    </h1>

  </body>
</html>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= t(".expert") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a href="<%= root_path %>">
          <span class="navbar-item has-text-weight-bold is-size-4">
            <%= t(".expert") %>
          </span>
          </a>

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <% unless user_signed_in? %>
                <%= link_to t(".sign_in"), new_user_session_path, class: "button is-light" %>
                <% else %>
                <%= link_to t(".new_item"), new_item_path, class: "button is-light" %>
                <%=link_to t(".sign_out"), destroy_user_session_path, data: { "turbo-method": :delete }, class: "button is-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>
      
      <div class="main">
        <p style="color: green"><%= notice %></p>
        <p  style="color: red"><%= alert %></p>
        <%= yield %>
      </div>
      
      
    </div>
  </section>
  </body>
</html>

app/views/monitems/_form.html.erb
<%= form_with(model: [monitem.item, monitem]) do |form| %>
  <% if monitem.errors.any? %>
    <div style="color: red">
      <h2>保存时发现 <%= pluralize(monitem.errors.count, "个错误") %>：</h2>

      <ul>
        <% monitem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id, readonly: true %>
    <br>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
    <br>
  </div>

  <div>
    <%= form.label :alias_name, style: "display: block" %>
    <%= form.text_field :alias_name %>
    <br>
  </div>

  <div>
    <%= form.label :nation, style: "display: block" %>
    <%= form.text_field :nation %>
    <br>
  </div>

  <div>
    <%= form.label :birthplace, style: "display: block" %>
    <%= form.text_field :birthplace %>
    <br>
  </div>

  <div>
    <%= form.label :occupation, style: "display: block" %>
    <%= form.text_field :occupation %>
    <br>
  </div>

  <div>
    <%= form.label :biographical_text, style: "display: block" %>
    <%= form.text_area :biographical_text, rows: 5 %>
    <br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/monitems/_monitem.html.erb
<div id="<%= dom_id monitem %>">
  <p>
    <strong><%= t(".item") %></strong>
    <%= monitem.item.name %>
  </p>

  <p>
    <strong><%= t(".name") %></strong>
    <%= monitem.name %>
  </p>

  <p>
    <strong><%= t(".alias_name") %></strong>
    <%= monitem.alias_name %>
  </p>

  <p>
    <strong><%= t(".nation") %></strong>
    <%= monitem.nation %>
  </p>

  <p>
    <strong><%= t(".birthplace") %></strong>
    <%= monitem.birthplace %>
  </p>

  <p>
    <strong><%= t(".occupation") %></strong>
    <%= monitem.occupation %>
  </p>

  <p>
    <strong><%= t(".biographical_text") %></strong>
    <%= monitem.biographical_text %>
  </p>

</div>

app/views/monitems/edit.html.erb
<div class="mgl my-6 py-6">
 <h1 class="title px-6"><%= t(".editing_monitem") %></h1>

  <%= render "form", monitem: @monitem %>

  <br>

  <div>
    <%= link_to t(".show_this_monitem"), [@monitem.item, @monitem] %> |
    <%= link_to t(".back_to_item"), item_path(@monitem.item) %>
  </div>
</div>

app/views/monitems/index.html.erb
<div class="mgl my-6 py-6">

<h1 class="title"><%= @item.name %></h1>

<div id="monitems">
  <% @monitems.each do |monitem| %>
    <%= render monitem %>
    <p>
      <%= link_to "Show this monitem", [monitem.item, monitem] %>
    </p>
  <% end %>
</div>

</div>

app/views/monitems/new.html.erb
<div class="mgl my-6 py-6">
 
 <h1 class="title px-6"><%= t(".new_monitem") %></h1>

  <%= render "form", monitem: @monitem %>

  <br>

  <div>
    <%= link_to t(".back_to_item"), item_path(@item) %>
  </div>

</div>

app/views/monitems/show.html.erb
<div class="mgl my-6 px-6">

<%= render @monitem %>
  <% if user_signed_in? %>
  <div>
    <%= link_to t(".edit_this_monitem"), edit_item_monitem_path(@monitem.item, @monitem) %> |
    <%= link_to t(".back_to_item"), item_path(@item) %>
    <%= button_to t(".destroy_this_monitem"), [@monitem.item, @monitem], method: :delete, data: {"turbo-confirm": "您确认要删除该信息吗？"} %>
  </div>
  <% end %>
</div>